name: Build Map Generator with Pygbag
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Python Map Generator
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
        echo "Attempting to install pygbag"
        python3 -m pip install -U pygame --user
        pip install pygame pygbag
        pip install numpy
        pip install asyncio
        echo "Successfully installed pygbag"
        echo "Attempting to build the game"
        python -m pygbag --build MapGenerator.py
        echo "Successfully build the game and complied to WebAssembly"
        ls
    - name : "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/web