name: Build Map Generator with Pygbag
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Python Map Generator
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
        echo "Attempting to install pygbag"
        python -m pip install pygbag
        echo "Successfully installed pygbag"
        echo "Attempting to build the game"
        python -m pygbag --build MapGenerator.py
        echo "Successfully build the game and complied to WebAssembly"
        ls
    # Deployment
    - name: Stash build result and reset local changes
      run: |
        echo "Applying initial configs"
        sudo chown -R $USER:$USER ${{ vars.BUILD_PATH }}
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        echo "Stash and reset"
        git add ${{ vars.BUILD_PATH }}
        git stash push ${{ vars.BUILD_PATH }}
        git stash list
        git reset --hard
        sudo git clean -d -x -f
    # Deployment
    - name: Cleaning gh-pages branch
      run: |
        
        echo "Switch to ${{ vars.DEPLOYMENT_BRANCH }}"
        git pull
        git checkout ${{ vars.DEPLOYMENT_BRANCH }}
        git reset --hard
        sudo git clean -d -x -f
    - name: Applying stashed files to ${{ vars.DEPLOYMENT_BRANCH }}
      run: |
        echo "Applying stash"
        git stash apply stash@{0}
    - name: Copying files to root directory
      run: |
        cd ${{ vars.BUILD_PATH }}
        ls
        cp -r * ../
        cd ../
        rm -r ${{ vars.BUILD_PATH }}
        ls
        pwd
    - name: Pushing deployment to gh-pages branch
      run: |
        pwd
        git status
        git add *
        git commit -m "Deployment"
        git push
        git reset --hard
        sudo git clean -d -x -f